global using BuildingBlocks.CQRS;
global using BuildingBlocks.Results;
global using Order.Application.Dtos;
global using BuildingBlocks.Messaging.Events;
global using BuildingBlocks.Repository;
global using FluentValidation;
global using MassTransit;
global using Microsoft.EntityFrameworkCore;
global using Order.Domain.ValueObjects;
global using BuildingBlocks.Identity;
global using Microsoft.Extensions.Logging;
global using Order.Domain.Models;
global using BuildingBlocks.Observability.ApiResponse;
global using BuildingBlocks.Observability.Constants;
global using Order.Application.Commons;
global using AutoMapper;
global using BuildingBlocks.Observability.Pagination;
global using System.Linq.Expressions;
global using System.Net;
global using DomainOrder = Order.Domain.Models.Order;
global using OrderEntity = Order.Domain.Models.Order;