<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="NewFolder\**" />
    <Compile Remove="Protos\**" />
    <EmbeddedResource Remove="NewFolder\**" />
    <EmbeddedResource Remove="Protos\**" />
    <None Remove="NewFolder\**" />
    <None Remove="Protos\**" />
  </ItemGroup>
	<ItemGroup>
		<PackageReference Include="AWSSDK.S3" Version="4.0.19.1" />
		<PackageReference Include="Bogus" Version="35.6.5" />
		<PackageReference Include="EFCore.BulkExtensions" Version="8.1.2" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.15" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="8.0.14" />
		<PackageReference Include="Elastic.Clients.Elasticsearch" Version="8.15.6" />
		<PackageReference Include="Hangfire.Core" Version="1.8.14" />
		<PackageReference Include="Hangfire.AspNetCore" Version="1.8.14" />
		<PackageReference Include="Hangfire.PostgreSql" Version="1.20.9" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.14">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>
	<ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="8.0.0" />
	<PackageReference Include="Grpc.AspNetCore" Version="2.57.0" />
	</ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\BuildingBlocks\BuildingBlocks.csproj" />
    <ProjectReference Include="..\Production.Application\Production.Application.csproj" />
    <ProjectReference Include="..\Production.Domain\Production.Domain.csproj" />
  </ItemGroup>
	<ItemGroup>
		<Protobuf Include="Grpc\Protos\product.proto" GrpcServices="Server" />
	</ItemGroup>

</Project>
